### ISSUE TITLE
Drag and Drop not working in FreeH

### ISSUE THREAD

**Issue by happysad2021** [IllusionMods/DragAndDrop#10]
I have the latest version installed and in freeH when i drag a card from explorer or koicatalog, it would shows "no even handler in this event" on top left corner, with the female character unchanged.

I have also installed Kplug, not sure if this could be the reason. I also installed mods and plugin with latest version from KKmanager

**Comment by ManlyMarco** [comment]
Make sure you are using the latest version of the plugin.

**Comment by happysad2021** [comment]
![koi bug](https://user-images.githubusercontent.com/104582373/165885261-4932ef38-8c3e-4bb6-83ec-db5a082af016.JPG)
![koi 2](https://user-images.githubusercontent.com/104582373/165885268-ad0ac5d0-554c-464b-857d-7221c978318e.JPG)
I have installed the latest version as seen from attached.
And when i drag a working character card, the error is shown as attached at top left.

**Comment by ManlyMarco** [comment]
You can't use this plugin inside of the H scene, only on the Free H selection screen.
