### ISSUE TITLE
Koikatsu Drag and drop it's not working

### ISSUE THREAD

**Issue by Onikiller** [IllusionMods/DragAndDrop#11]
Soo, in character creation window, when i drag a card to the game window nothing happen. I have tryed with new and old cards, same result. All the cards works if i put in the female folder. Latest HF-Patch installed and r i have downloaded again from here and same results.

-Ps: Free roam mode(AKA school, dind try scene mod because i dont play it...)

-Ps2: Sorry for my english.

**Comment by ManlyMarco** [comment]
Post output_log file from game directory after triggering the bug.
