### ISSUE TITLE
Doesn't work with coordinate cards

### ISSUE THREAD

**Issue by SeraphHsing** [IllusionMods/DragAndDrop#4]
Seems chara cards works fine, but coordinate crads couldn't load when dragging it to game window in AIGirl Maker.

**Comment by Keelhauled** [comment]
Coordinate cards are not supported at the moment it seems but it could be added.

**Comment by ManlyMarco** [comment]
I think this should be kept open until coordinate card dropping is added, assuming it's added.

**Comment by ManlyMarco** [comment]
Partial solution in 2ad81796abef9ae0b2a2a9370bbd286d4d4601db
