### ISSUE TITLE
Plugin not working within HF Patch on Koikatsu Party

### ISSUE THREAD

**Issue by funcontent** [IllusionMods/DragAndDrop#7]
When I go to drag a character card (.png) into the male/female character editor the mouse changes (normally changes to red crossout if the application does not support drag and drop)as if I can drag files but when the file is dropped nothing happens. I have verified that drag and drop is working with other applications. I have the latest version of HF patch (v3.11). I am using Koikatsu party steam version.

**Comment by ManlyMarco** [comment]
Make sure neither the game nor explorer are running as administrator. Try different cards or check log/console to make sure the card isn't the problem.

**Comment by funcontent** [comment]
I was able to fix the issue. The program was running with admin privilege's for some reason. Unfortunately while trying to use debug console to fix the issue it came up with warning that I ran out of GUI? This caused the game to freeze and even after restarting I was unable to play. I just ended up coping my chara and game save and just fresh reinstalling. It worked after the fresh install.
