### ISSUE TITLE
Coordinates not loading in KK studio and maker anymore

### ISSUE THREAD

**Issue by Timo713** [IllusionMods/DragAndDrop#9]
After updating to 1.2.6, I noticed I couldn't replace outfits by simply dragging the coordinates into the game window, but it still works with the previous versions, the same thing may happen with KKS.

**Comment by ManlyMarco** [comment]
Can you give examples of some cards that fail to load, and the output_log.txt file from after it happens?

**Comment by Timo713** [comment]
It happens with every coordinate card. Here's the output_log.txt after trying to load one of the default coordinates into a chika card in the studio. I'll include the coordinate too.

[output_log.txt](https://github.com/IllusionMods/DragAndDrop/files/7707655/output_log.txt)
![私服](https://user-images.githubusercontent.com/60951827/145908574-087ee095-4cda-45f3-b3ba-8e9ff7c1904a.png)

**Comment by Timo713** [comment]
In comparison, here's the log of doing the same process but in v1.2.5
[output_log.txt](https://github.com/IllusionMods/DragAndDrop/files/7707665/output_log.txt)

**Comment by ManlyMarco** [comment]
It looks like the coordinate is being loaded normally in the log, maybe try removing BonerStateSync and JetPack and see if that changes anything. There's also some crashes at the start that usually mean you have a plugin for KKS or other incompatible game installed in your KK plugins folder, so that might also be the cause.

**Comment by Timo713** [comment]
I removed both plugins but still not working. I also tested with a clean KKS install and your newest HF patch (only by updating this plugin), still nothing.

**Comment by ManlyMarco** [comment]
[bin.zip](https://github.com/IllusionMods/DragAndDrop/files/7736937/bin.zip)
Can you try this build?

**Comment by Timo713** [comment]
I tested KK and KKS. It's working again, thank you! This plugin is really useful for importing stuff.

Just a quick question, although this counts as an enhancement. Do you think it is possible, or do you have any plan to add the same feature for adding cards into the main game class roster/rooms?
